obj-y += timer.o
obj-y += clock.o clock-voter.o clock-dummy.o
obj-y += platsmp.o
obj-y += board-ipq806x.o clock-ipq806x.o
obj-y += dma.o gpiomux-v2.o gpiomux.o platsmp.o
obj-y += mpm.o
obj-y += rpm-ipq806x.o
obj-y += acpuclock.o
obj-y += acpuclock-krait.o
obj-y += acpuclock-ipq806x.o
obj-y += msm-krait-l2-accessors.o
obj-y += clock-local.o clock-rpm.o clock-pll.o
obj-y += rb3011-voltage-regulator.o

obj-$(CONFIG_CPU_FREQ_MSM) += cpufreq.o
obj-$(CONFIG_MSM_RPM) += rpm.o rpm_resources.o rpm-debug.o
obj-$(CONFIG_MSM_PCIE) += pcie.o pcie_irq.o pcie-ipq806x.o
obj-$(CONFIG_MSM_BUS_SCALING) += msm_bus/
