#include <linux/errno.h>
#include <mach/msm_iomap.h>
#include <mach/irqs.h>

#include "rpm_resources.h"
#include "clock.h"
#include "pm.h"

static struct msm_rpmrs_level msm_rpmrs_levels[] = {
	{
		MSM_PM_SLEEP_MODE_WAIT_FOR_INTERRUPT,
		MSM_RPMRS_LIMITS(ON, ACTIVE, MAX, ACTIVE),
		true,
		1, 784, 180000, 100,
	},

	{
		MSM_PM_SLEEP_MODE_RETENTION,
		MSM_RPMRS_LIMITS(ON, ACTIVE, MAX, ACTIVE),
		true,
		415, 715, 340827, 475,
	},

	{
		MSM_PM_SLEEP_MODE_POWER_COLLAPSE_STANDALONE,
		MSM_RPMRS_LIMITS(ON, ACTIVE, MAX, ACTIVE),
		true,
		1300, 228, 1200000, 2000,
	},

	{
		MSM_PM_SLEEP_MODE_POWER_COLLAPSE,
		MSM_RPMRS_LIMITS(ON, GDHS, MAX, ACTIVE),
		false,
		2000, 138, 1208400, 3200,
	},

	{
		MSM_PM_SLEEP_MODE_POWER_COLLAPSE,
		MSM_RPMRS_LIMITS(ON, HSFS_OPEN, ACTIVE, RET_HIGH),
		false,
		6000, 119, 1850300, 9000,
	},

	{
		MSM_PM_SLEEP_MODE_POWER_COLLAPSE,
		MSM_RPMRS_LIMITS(OFF, GDHS, MAX, ACTIVE),
		false,
		9200, 68, 2839200, 16400,
	},

	{
		MSM_PM_SLEEP_MODE_POWER_COLLAPSE,
		MSM_RPMRS_LIMITS(OFF, HSFS_OPEN, MAX, ACTIVE),
		false,
		10300, 63, 3128000, 18200,
	},

	{
		MSM_PM_SLEEP_MODE_POWER_COLLAPSE,
		MSM_RPMRS_LIMITS(OFF, HSFS_OPEN, ACTIVE, RET_HIGH),
		false,
		18000, 10, 4602600, 27000,
	},

	{
		MSM_PM_SLEEP_MODE_POWER_COLLAPSE,
		MSM_RPMRS_LIMITS(OFF, HSFS_OPEN, RET_HIGH, RET_LOW),
		false,
		20000, 2, 5752000, 32000,
	},
};

static struct msm_rpmrs_platform_data msm_rpmrs_data __initdata = {
	.levels = &msm_rpmrs_levels[0],
	.num_levels = ARRAY_SIZE(msm_rpmrs_levels),
	.vdd_mem_levels  = {
		[MSM_RPMRS_VDD_MEM_RET_LOW]	= 750000,
		[MSM_RPMRS_VDD_MEM_RET_HIGH]	= 750000,
		[MSM_RPMRS_VDD_MEM_ACTIVE]	= 1050000,
		[MSM_RPMRS_VDD_MEM_MAX]		= 1150000,
	},
	.vdd_dig_levels = {
		[MSM_RPMRS_VDD_DIG_RET_LOW]	= 500000,
		[MSM_RPMRS_VDD_DIG_RET_HIGH]	= 750000,
		[MSM_RPMRS_VDD_DIG_ACTIVE]	= 950000,
		[MSM_RPMRS_VDD_DIG_MAX]		= 1150000,
	},
	.vdd_mask = 0x7FFFFF,
	.rpmrs_target_id = {
		[MSM_RPMRS_ID_PXO_CLK]		= MSM_RPM_ID_PXO_CLK,
		[MSM_RPMRS_ID_L2_CACHE_CTL]	= MSM_RPM_ID_LAST,
		[MSM_RPMRS_ID_VDD_DIG_0]	= MSM_RPM_ID_SMB208_S1b_0,
		[MSM_RPMRS_ID_VDD_DIG_1]	= MSM_RPM_ID_SMB208_S1b_1,
		[MSM_RPMRS_ID_VDD_MEM_0]	= MSM_RPM_ID_SMB208_S1b_0,
		[MSM_RPMRS_ID_VDD_MEM_1]	= MSM_RPM_ID_SMB208_S1b_1,
		[MSM_RPMRS_ID_RPM_CTL]		= MSM_RPM_ID_RPM_CTL,
	},
};

struct msm_rpm_platform_data ipq806x_rpm_data __initdata = {
	.reg_base_addrs = {
		[MSM_RPM_PAGE_STATUS] = MSM_RPM_BASE,
		[MSM_RPM_PAGE_CTRL] = MSM_RPM_BASE + 0x400,
		[MSM_RPM_PAGE_REQ] = MSM_RPM_BASE + 0x600,
		[MSM_RPM_PAGE_ACK] = MSM_RPM_BASE + 0xa00,
	},
	.irq_ack = RPM_APCC_CPU0_GP_HIGH_IRQ,
	.irq_err = RPM_APCC_CPU0_GP_LOW_IRQ,
	.irq_wakeup = RPM_APCC_CPU0_WAKE_UP_IRQ,
	.ipc_rpm_reg = MSM_APCS_GCC_BASE + 0x008,
	.ipc_rpm_val = 4,
	.target_id =  {
		MSM_RPM_MAP(IPQ806X, NOTIFICATION_CONFIGURED_0, NOTIFICATION, 4, "notification_configured"),
		MSM_RPM_MAP(IPQ806X, NOTIFICATION_REGISTERED_0, NOTIFICATION, 4, "notification_registered"),
		MSM_RPM_MAP(IPQ806X, INVALIDATE_0, INVALIDATE, 8, "invalidate"),
		MSM_RPM_MAP(IPQ806X, TRIGGER_TIMED_TO, TRIGGER_TIMED, 1, "trigger_timed_to"),
		MSM_RPM_MAP(IPQ806X, TRIGGER_TIMED_SCLK_COUNT, TRIGGER_TIMED, 1, "trigger_timed_sclk_count"),
		MSM_RPM_MAP(IPQ806X, RPM_CTL, RPM_CTL, 1, "rpm_ctl"),
		MSM_RPM_MAP(IPQ806X, CXO_CLK, CXO_CLK, 1, "cxo_clk"),
		MSM_RPM_MAP(IPQ806X, PXO_CLK, PXO_CLK, 1, "pxo_clk"),
		MSM_RPM_MAP(IPQ806X, APPS_FABRIC_CLK, APPS_FABRIC_CLK, 1, "apps_fabric_clk"),
		MSM_RPM_MAP(IPQ806X, SYSTEM_FABRIC_CLK, SYSTEM_FABRIC_CLK, 1, "system_fabric_clk"),
		MSM_RPM_MAP(IPQ806X, MM_FABRIC_CLK, MM_FABRIC_CLK, 1, "mm_fabric_clk"),
		MSM_RPM_MAP(IPQ806X, DAYTONA_FABRIC_CLK, DAYTONA_FABRIC_CLK, 1, "daytona_fabric_clk"),
		MSM_RPM_MAP(IPQ806X, SFPB_CLK, SFPB_CLK, 1, "sfpb_clk"),
		MSM_RPM_MAP(IPQ806X, CFPB_CLK, CFPB_CLK, 1, "cfpb_clk"),
		MSM_RPM_MAP(IPQ806X, MMFPB_CLK, MMFPB_CLK, 1, "mmfpb_clk"),
		MSM_RPM_MAP(IPQ806X, EBI1_CLK, EBI1_CLK, 1, "ebi1_clk"),
		MSM_RPM_MAP(IPQ806X, APPS_FABRIC_CFG_HALT_0,
				APPS_FABRIC_CFG_HALT, 2, "apps_fabric_cfg_halt"),
		MSM_RPM_MAP(IPQ806X, APPS_FABRIC_CFG_CLKMOD_0,
				APPS_FABRIC_CFG_CLKMOD, 3, "apps_fabric_cfg_clkmod" ),
		MSM_RPM_MAP(IPQ806X, APPS_FABRIC_CFG_IOCTL,
				APPS_FABRIC_CFG_IOCTL, 1, "apps_fabric_cfg_ioctl" ),
		MSM_RPM_MAP(IPQ806X, APPS_FABRIC_ARB_0, APPS_FABRIC_ARB, 12, "apps_fabric_arb"),
		MSM_RPM_MAP(IPQ806X, SYS_FABRIC_CFG_HALT_0,
				SYS_FABRIC_CFG_HALT, 2, "sys_fabric_cfg_halt" ),
		MSM_RPM_MAP(IPQ806X, SYS_FABRIC_CFG_CLKMOD_0,
				SYS_FABRIC_CFG_CLKMOD, 3, "sys_fabric_cfg_clkmod" ),
		MSM_RPM_MAP(IPQ806X, SYS_FABRIC_CFG_IOCTL,
				SYS_FABRIC_CFG_IOCTL, 1, "sys_fabric_cfg_ioctl" ),
		MSM_RPM_MAP(IPQ806X, SYSTEM_FABRIC_ARB_0, SYSTEM_FABRIC_ARB, 30, "system_fabric_arb"),
		MSM_RPM_MAP(IPQ806X, MMSS_FABRIC_CFG_HALT_0,
				MMSS_FABRIC_CFG_HALT, 2, "mmss_fabric_cfg_halt" ),
		MSM_RPM_MAP(IPQ806X, MMSS_FABRIC_CFG_CLKMOD_0,
				MMSS_FABRIC_CFG_CLKMOD, 3, "mmss_fabric_cfg_clkmod" ),
		MSM_RPM_MAP(IPQ806X, MMSS_FABRIC_CFG_IOCTL,
				MMSS_FABRIC_CFG_IOCTL, 1, "mmss_fabric_cfg_ioctl" ),
		MSM_RPM_MAP(IPQ806X, MM_FABRIC_ARB_0, MM_FABRIC_ARB, 2, "mm_fabric_arb"),

		MSM_RPM_MAP(IPQ806X, NCP_0, NCP, 2, "ncp"),
		MSM_RPM_MAP(IPQ806X, CXO_BUFFERS, CXO_BUFFERS, 1, "cxo_buffers"),
		MSM_RPM_MAP(IPQ806X, USB_OTG_SWITCH, USB_OTG_SWITCH, 1, "usb_otg_switch"),
		MSM_RPM_MAP(IPQ806X, HDMI_SWITCH, HDMI_SWITCH, 1, "hdmi_switch"),
		MSM_RPM_MAP(IPQ806X, DDR_DMM_0, DDR_DMM, 2, "ddr_dmm"),
		MSM_RPM_MAP(IPQ806X, QDSS_CLK, QDSS_CLK, 1, "qdss_clk"),
		MSM_RPM_MAP(IPQ806X, VDDMIN_GPIO, VDDMIN_GPIO, 1, "vddmin_gpio"),

		MSM_RPM_MAP(IPQ806X, SMB208_S1a_0, SMB208_S1a, 2, "smb208_s1a"),
		MSM_RPM_MAP(IPQ806X, SMB208_S1b_0, SMB208_S1b, 2, "smb208_s1b"),
		MSM_RPM_MAP(IPQ806X, SMB208_S2a_0, SMB208_S2a, 2, "smb208_s2a"),
		MSM_RPM_MAP(IPQ806X, SMB208_S2b_0, SMB208_S2b, 2, "smb208_s2b"),
		MSM_RPM_MAP(IPQ806X, SMB208_S3a_0, SMB208_S3a, 2, "smb208_s3a"),
		MSM_RPM_MAP(IPQ806X, SMB208_S3b_0, SMB208_S3b, 2, "smb208_s3b"),

		MSM_RPM_MAP(IPQ806X, DDR_SELF_REFRESH, DDR_SELF_REFRESH, 1, "ddr_self_refresh"),
		MSM_RPM_MAP(IPQ806X, ENTER_IDLE, ENTER_IDLE, 2, "enter_idle"),
	},
	.target_status = {
		MSM_RPM_STATUS_ID_MAP(IPQ806X, VERSION_MAJOR),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, VERSION_MINOR),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, VERSION_BUILD),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, SUPPORTED_RESOURCES_0),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, SUPPORTED_RESOURCES_1),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, SUPPORTED_RESOURCES_2),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, RESERVED_SUPPORTED_RESOURCES_0),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, SEQUENCE),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, RPM_CTL),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, CXO_CLK),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, PXO_CLK),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, APPS_FABRIC_CLK),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, SYSTEM_FABRIC_CLK),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, MM_FABRIC_CLK),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, DAYTONA_FABRIC_CLK),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, SFPB_CLK),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, CFPB_CLK),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, MMFPB_CLK),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, EBI1_CLK),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, APPS_FABRIC_CFG_HALT),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, APPS_FABRIC_CFG_CLKMOD),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, APPS_FABRIC_CFG_IOCTL),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, APPS_FABRIC_ARB),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, SYS_FABRIC_CFG_HALT),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, SYS_FABRIC_CFG_CLKMOD),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, SYS_FABRIC_CFG_IOCTL),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, SYSTEM_FABRIC_ARB),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, MMSS_FABRIC_CFG_HALT),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, MMSS_FABRIC_CFG_CLKMOD),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, MMSS_FABRIC_CFG_IOCTL),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, MM_FABRIC_ARB),

		MSM_RPM_STATUS_ID_MAP(IPQ806X, NCP_0),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, NCP_1),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, CXO_BUFFERS),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, USB_OTG_SWITCH),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, HDMI_SWITCH),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, DDR_DMM_0),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, DDR_DMM_1),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, EBI1_CH0_RANGE),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, EBI1_CH1_RANGE),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, VDDMIN_GPIO),

		MSM_RPM_STATUS_ID_MAP(IPQ806X, SMB208_S1a_0),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, SMB208_S1a_1),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, SMB208_S1b_0),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, SMB208_S1b_1),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, SMB208_S2a_0),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, SMB208_S2a_1),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, SMB208_S2b_0),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, SMB208_S2b_1),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, SMB208_S3a_0),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, SMB208_S3a_1),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, SMB208_S3b_0),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, SMB208_S3b_1),

		MSM_RPM_STATUS_ID_MAP(IPQ806X, DDR_SELF_REFRESH),
		MSM_RPM_STATUS_ID_MAP(IPQ806X, ENTER_IDLE),
	},
	.target_ctrl_id = {
		MSM_RPM_CTRL_MAP(IPQ806X, VERSION_MAJOR),
		MSM_RPM_CTRL_MAP(IPQ806X, VERSION_MINOR),
		MSM_RPM_CTRL_MAP(IPQ806X, VERSION_BUILD),
		MSM_RPM_CTRL_MAP(IPQ806X, REQ_CTX_0),
		MSM_RPM_CTRL_MAP(IPQ806X, REQ_SEL_0),
		MSM_RPM_CTRL_MAP(IPQ806X, ACK_CTX_0),
		MSM_RPM_CTRL_MAP(IPQ806X, ACK_SEL_0),
	},
	.sel_invalidate = MSM_RPM_IPQ806X_SEL_INVALIDATE,
	.sel_notification = MSM_RPM_IPQ806X_SEL_NOTIFICATION,
	.sel_last = MSM_RPM_IPQ806X_SEL_LAST,
	.ver = {3, 0, 0},
};

void __init ipq806x_rpm_init(void) {
    msm_rpm_init(&ipq806x_rpm_data);
    msm_rpmrs_levels_init(&msm_rpmrs_data);
    msm_clock_init(&ipq806x_clock_init_data);
}
